"""
vocalis/core/dispatcher.py — Tool declarations & function call router.

Defines the two tools Gemini Live API can call:
  1. dispatch_job     — Heavy-path: async background agent work
  2. get_system_telemetry — Fast-path: instant system stats

CRITICAL CONSTRAINT (Live API):
  Function calling is SYNCHRONOUS. Gemini will NOT speak until we
  return the tool response. So tool handlers must be instantaneous —
  < 10ms. The actual background work is spawned AFTER the response.
"""
from __future__ import annotations

import json
from typing import Any

from google.genai import types

from vocalis.jobs.registry import JobRegistry
from vocalis.tools.telemetry import get_telemetry


# ──────────────────────────────────────────────
# Tool Declarations (sent to Gemini on session open)
# ──────────────────────────────────────────────

TOOL_DECLARATIONS = types.Tool(
    function_declarations=[
        types.FunctionDeclaration(
            name="dispatch_job",
            description=(
                "Dispatch a complex task — coding, system administration, research, "
                "audits, or multi-step execution — to a specialist background agent. "
                "The job runs asynchronously. Use this for anything that takes more "
                "than a few seconds to complete."
            ),
            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    "target_agent": types.Schema(
                        type=types.Type.STRING,
                        description=(
                            "The specialist agent best suited for the task. "
                            "One of: win_janitor, campaigns, repo_architect, "
                            "research, general_worker"
                        ),
                        enum=[
                            "win_janitor",
                            "campaigns",
                            "repo_architect",
                            "google_workspace",
                            "play_console",
                            "telegram_nexus",
                            "general_worker",
                        ],
                    ),
                    "title": types.Schema(
                        type=types.Type.STRING,
                        description="Short human-readable title for the job (max 60 chars)",
                    ),
                    "prompt": types.Schema(
                        type=types.Type.STRING,
                        description="Detailed instructions for the worker agent",
                    ),
                    "priority": types.Schema(
                        type=types.Type.STRING,
                        description="Job priority level",
                        enum=["normal", "high", "critical"],
                    ),
                },
                required=["target_agent", "title", "prompt"],
            ),
        ),
        types.FunctionDeclaration(
            name="get_system_telemetry",
            description=(
                "Get real-time system metrics or campaign data. "
                "Returns instant data — no background work needed."
            ),
            parameters=types.Schema(
                type=types.Type.OBJECT,
                properties={
                    "metric": types.Schema(
                        type=types.Type.STRING,
                        description="Which metric to fetch",
                        enum=["ram", "cpu", "strikes", "treasury", "all"],
                    ),
                },
                required=["metric"],
            ),
        ),
    ]
)


# ──────────────────────────────────────────────
# Function Call Router
# ──────────────────────────────────────────────

def handle_tool_call(name: str, args: dict[str, Any]) -> str:
    """
    Route an incoming function call from Gemini to the correct handler.
    Returns a JSON string as the tool response.

    MUST be fast (< 50ms) — Gemini blocks spoken output until this returns.
    Background work is spawned asynchronously AFTER this function returns.
    """
    if name == "dispatch_job":
        return _handle_dispatch_job(args)
    elif name == "get_system_telemetry":
        return _handle_telemetry(args)
    else:
        return json.dumps({"error": f"Unknown tool: {name}"})


def _handle_dispatch_job(args: dict[str, Any]) -> str:
    """
    Create a job ticket immediately, spawn background worker, return receipt.
    The verbal ACK ("JOB-42 dispatched") is generated by Gemini from our response.
    """
    registry = JobRegistry()
    job = registry.create(
        agent=args["target_agent"],
        title=args["title"],
        prompt=args["prompt"],
        priority=args.get("priority", "normal"),
    )

    # Spawn background worker AFTER creating the ticket
    # Import here to avoid circular deps
    from vocalis.jobs.worker import spawn_worker
    spawn_worker(job)

    return json.dumps({
        "job_id": job["id"],
        "agent": job["agent"],
        "status": "queued",
        "message": f"{job['id']} assigned to {job['agent']}. Running in background.",
    })


def _handle_telemetry(args: dict[str, Any]) -> str:
    """Fetch live system metrics — instant, no background work."""
    metric = args.get("metric", "all")
    data = get_telemetry(metric)
    return json.dumps(data)
